config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get '/info' => 'info#index'
  devise_for :users
  # devise_for :users, :controllers => {
  #   :sessions      => "users/sessions",
  #   :registrations => "users/registrations",
  #   :passwords     => "users/passwords",
  # }
  resources :products do
    member do
      post :add_to_cart
      post :favorite
      post :unfavorite
      post :instant_buy
    end
    collection do
      get :my_course
      get :search
    end
    resources :reviews, only: [:new, :create]
  end

  namespace :admin do
    resources :quizzes do
      resources :questions
    end
    resources :categories
    resources :products
    resources :posts
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end


  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :cart_items

  resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end

  namespace :account do
    resources :orders
  end

  resources :favorites


  resources :quizzes do
    member do
      post :exam_records
    end
    resources :questions
  end

  root "welcome#index"

  get 'about' => 'welcome#about'

  post "set_answer_1_status" => "answers#set_answer_1_status"
  post "set_answer_2_status" => "answers#set_answer_2_status"
  post "set_answer_3_status" => "answers#set_answer_3_status"
  post "set_answer_4_status" => "answers#set_answer_4_status"


end

app/models/exam.rb
class Exam < ApplicationRecord

  has_many :answers

  belongs_to :quiz
  belongs_to :user

end

app/controllers/admin/exams_controller.rb
class Admin::ExamsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_required
  layout "admin"

  def index
    @exams = Exam.all
    @choice = Choice.new
    @choices = Choice.all
  end

  def new
    @exam = Exam.new
    @categories = Category.all.map { |c| [c.name, c.id] }
    @choice = Choice.new
  end

  def show
    @exam = Exam.find(params[:id])
    @exam.category_id = params[:category_id]
  end

  def edit
    @exam = Exam.find(params[:id])
    @categories = Category.all.map { |c| [c.name, c.id] }
    @choice = Choice.new
  end

  def create
    @exam = Exam.create(exam_params)
    @exam.category_id = params[:category_id]

    if @exam.save
      redirect_to admin_exams_path,notice:"创建成功！"
    else
      render :new
    end
  end

  def update
    @exam = Exam.find(params[:id])


    if @exam.update(exam_params)
      redirect_to admin_exams_path
    else
      render :edit
    end
  end

  def destroy
    @exam = Exam.find(params[:id])
    @exam.destroy
    flash[:alert] = "exam Deleted"
    redirect_to admin_exams_path
  end

 def a
    @exam = Exam.find(params[:id])
    @exam.a!
    redirect_to :back
 end
 def a1
    @exam = Exam.find(params[:id])
    @exam.a1!
    redirect_to :back
 end

 def b
    @exam = Exam.find(params[:id])
    @exam.b!
    redirect_to :back
 end
 def b1
    @exam = Exam.find(params[:id])
    @exam.b1!
    redirect_to :back
 end

 def c
    @exam = Exam.find(params[:id])
    @exam.c!
    redirect_to :back
 end
 def c1
    @exam = Exam.find(params[:id])
    @exam.c1!
    redirect_to :back
 end

 def d
    @exam = Exam.find(params[:id])
    @exam.d!
    redirect_to :back
 end
 def d1
    @exam = Exam.find(params[:id])
    @exam.d1!
    redirect_to :back
 end

 def e
    @exam = Exam.find(params[:id])
    @exam.e!
    redirect_to :back
 end
 def e1
    @exam = Exam.find(params[:id])
    @exam.e1!
    redirect_to :back
 end

 def f
    @exam = Exam.find(params[:id])
    @exam.f!
    redirect_to :back
 end
 def f1
    @exam = Exam.find(params[:id])
    @exam.f1!
    redirect_to :back
 end

  private

  def exam_params
    params.require(:exam).permit(:name, :question, :answer_1,:answer_2,:answer_3,:answer_4,:answer_5,:answer_6,
                                 :image, :countdown, :is_a1en,:is_b1en,:is_c1en,:is_d1en,:is_e1en,:is_f1en)
  end


end

app/helpers/admin/exams_helper.rb
module Admin::ExamsHelper
end

app/helpers/exams_helper.rb
module ExamsHelper

    def render_a1_status(exam)
      if exam.is_a1en
        content_tag(:span, "", :class => "fa fa-check btn btn-xs btn-success")
      else
        content_tag(:span, "", :class => "fa fa-square-o btn btn-xs btn-warning")
      end
    end


    def render_b1_status(exam)
      if exam.is_b1en
        content_tag(:span, "", :class => "fa fa-check btn btn-xs btn-success")
      else
        content_tag(:span, "", :class => "fa fa-square-o btn btn-xs btn-warning")
      end
    end

    def render_c1_status(exam)
      if exam.is_c1en
        content_tag(:span, "", :class => "fa fa-check  btn btn-xs btn-success")
      else
        content_tag(:span, "", :class => "fa fa-square-o btn btn-xs btn-warning")
      end
    end

    def render_d1_status(exam)
      if exam.is_d1en
        content_tag(:span, "", :class => "fa fa-check  btn btn-xs btn-success")
      else
        content_tag(:span, "", :class => "fa fa-square-o btn btn-xs btn-warning")
      end
    end



    def render_e1_status(exam)
      if exam.is_e1en
        content_tag(:span, "", :class => "fa fa-check btn btn-xs btn-success")
      else
        content_tag(:span, "", :class => "fa fa-square-o btn btn-xs btn-warning")
      end
    end

    def render_f1_status(exam)
      if exam.is_f1en
        content_tag(:span, "", :class => "fa fa-check btn btn-xs btn-success")
      else
        content_tag(:span, "", :class => "fa fa-square-o btn btn-xs btn-warning")
      end
    end


end

app/views/admin/exams/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <h2 class="text-center">编辑试题</h2>
  <%= simple_form_for [:admin, @exam] do |f| %>
    <%= f.input :name, placeholder: "请输入试题xxx"%>
    <%= f.input :question, placeholder: "请输入试题题干" %>
    <%= f.input :answer_1, placeholder: "请输入试题描述" %><%= f.input :is_a1en, :label => "A" %>
    <%= f.input :answer_2, placeholder: "请输入试题描述" %><%= f.input :is_b1en, :label => "B" %>
    <%= f.input :answer_3, placeholder: "请输入试题描述" %><%= f.input :is_c1en, :label => "C" %>
    <%= f.input :answer_4, placeholder: "请输入试题描述" %><%= f.input :is_d1en, :label => "D" %>
    <%= f.input :answer_5, placeholder: "请输入试题描述" %><%= f.input :is_e1en, :label => "E" %>
    <%= f.input :answer_6, placeholder: "请输入试题描述" %><%= f.input :is_f1en, :label => "F" %>
    <%= f.select :category_id, @categories %>


    <div class="group"> <p><b>CountDownDate</b></p>
      <%= f.datetime_field :countdown %><br>
      <%= @exam.countdown %>
    </div>
    <%= f.label :image %><br>
    <%= f.file_field :image, :multiple => true, name: "photos[image][]" %>（"这里可以上传图片"）<br>
    <%= f.submit "Submit", class: "btn btn-default" %>
    <% end %>
    <%= simple_form_for [@choice] do |f| %>
      <%= f.input :name, placeholder: "请输入与试题相同的名字"%>
      <%= f.input :is_aa1en, :label => "A" %>
      <%= f.input :is_bb1en, :label => "B" %>
      <%= f.input :is_cc1en, :label => "C" %>
      <%= f.input :is_dd1en, :label => "D" %>
      <%= f.input :is_ee1en, :label => "E" %>
      <%= f.input :is_ff1en, :label => "F" %>
      <%= f.submit "Submit", class: "btn btn-default" %>
    <% end %>

</div>

app/views/admin/exams/index.html.erb
<h2> 考试题 </h2>
<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("新增试题", new_admin_exam_path, class: "btn btn-primary btn-sm") %>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>question</th>
      <th>answer</th>
      <th>true_answer</th>
      <th width="100"> Options </th>
      <td>试题代号 </td>
      <th>不做任何勾选，直接提交，且只能提交一次</th>
    </tr>
  </thead>
  <tbody>
    <% @exams.each do |exam| %>
    <tr>
      <td>
        <%= link_to exam.id, admin_exam_path(exam) %>
      </td>
       <td>
         <%= exam.question %>
       </td>
       <td>
         <%= exam.answer_1 %>
       </br><br>
         <%= exam.answer_2 %>
         <br><br>
         <%= exam.answer_3 %>
       </br><br>
         <%= exam.answer_4 %>
       <br><br>
         <%= exam.answer_5 %>
       </br><br>
         <%= exam.answer_6 %>
       </td>
       <td>

         <% if exam.is_a1en %>
         <%= link_to a_admin_exam_path(exam), method: :post, class: "btn btn-xs btn-success" do %>
         <i class="fa fa-check"></i><% end %>  A. <%= exam.answer_1 %>
         <% else %>
         <%= link_to a1_admin_exam_path(exam), method: :post, class: "btn btn-xs btn-warning" do %>
         <i class="fa fa-square-o"></i><% end %> A. <%= exam.answer_1 %>
         <% end %>
         <br><br>
         <% if exam.is_b1en %>
         <%= link_to b_admin_exam_path(exam), method: :post, class: "btn btn-xs btn-success" do %>
         <i class="fa fa-check"></i><% end %> B. <%= exam.answer_2 %>
         <% else %>
         <%= link_to b1_admin_exam_path(exam), method: :post, class: "btn btn-xs btn-warning" do %>
         <i class="fa fa-square-o"></i><% end %> B. <%= exam.answer_2 %>
         <% end %>
          <br><br>
         <% if exam.is_c1en %>
         <%= link_to c_admin_exam_path(exam), method: :post, class: "btn btn-xs btn-success" do %>
         <i class="fa fa-check"></i><% end %> C. <%= exam.answer_3 %>
         <% else %>
         <%= link_to c1_admin_exam_path(exam), method: :post, class: "btn btn-xs btn-warning" do %>
         <i class="fa fa-square-o"></i><% end %> C. <%= exam.answer_3 %>
         <% end %>
          <br><br>
         <% if exam.is_d1en %>
         <%= link_to d_admin_exam_path(exam), method: :post, class: "btn btn-xs btn-success" do %>
         <i class="fa fa-check"></i><% end %> D. <%= exam.answer_4 %>
         <% else %>
         <%= link_to d1_admin_exam_path(exam), method: :post, class: "btn btn-xs btn-warning" do %>
         <i class="fa fa-square-o"></i><% end %> D. <%= exam.answer_4 %>
         <% end %>
         <br><br>
        <% if exam.is_e1en %>
        <%= link_to e_admin_exam_path(exam), method: :post, class: "btn btn-xs btn-success" do %>
        <i class="fa fa-check"></i><% end %> E. <%= exam.answer_5 %>
        <% else %>
        <%= link_to e1_admin_exam_path(exam), method: :post, class: "btn btn-xs btn-warning" do %>
        <i class="fa fa-square-o"></i><% end %> E. <%= exam.answer_5 %>
        <% end %>
         <br><br>
        <% if exam.is_f1en %>
        <%= link_to f_admin_exam_path(exam), method: :post, class: "btn btn-xs btn-success" do %>
        <i class="fa fa-check"></i><% end %> F. <%= exam.answer_6 %>
        <% else %>
        <%= link_to f1_admin_exam_path(exam), method: :post, class: "btn btn-xs btn-warning" do %>
        <i class="fa fa-square-o"></i><% end %> F. <%= exam.answer_6 %>
        <% end %>

       </td>
       <td>
         <%= link_to("Edit", edit_admin_exam_path(exam)) %> |
         <%= link_to("Delete", admin_exam_path(exam), method: :delete, data: { confirm: "Are your sure?" }) %>
       </td>

       <td>
         <%= exam.name %>
       </td>

       <td>
           <%= simple_form_for @choice do |f| %>
           <input type="hidden" name="exam_id" value="<%= exam.id %>">
           <%= f.input :is_aa1en, :label => "A." %>
           <br>
           <%= f.input :is_bb1en, :label => "B." %>
           <br>
           <%= f.input :is_cc1en, :label => "C." %>
           <br>
           <%= f.input :is_dd1en, :label => "D." %>
           <%= f.submit "确定", class: "btn btn-info btn-info", data: {disable_with: "Submitting..."} %>
           <% end %>

       </td>



      <% end %>
     </tr>
   </tbody>
 </table>

app/views/admin/exams/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <h2 class="text-center">添加试题</h2>
  <%= simple_form_for [:admin, @exam] do |f| %>
    <%= f.input :name, placeholder: "请输入试题xxx"%>
    <%= f.input :question, placeholder: "请输入试题题干" %>
    <%= f.input :answer_1, placeholder: "请输入试题描述" %><%= f.input :is_a1en, :label => "A" %>
    <%= f.input :answer_2, placeholder: "请输入试题描述" %><%= f.input :is_b1en, :label => "B" %>
    <%= f.input :answer_3, placeholder: "请输入试题描述" %><%= f.input :is_c1en, :label => "C" %>
    <%= f.input :answer_4, placeholder: "请输入试题描述" %><%= f.input :is_d1en, :label => "D" %>
    <%= f.input :answer_5, placeholder: "请输入试题描述" %><%= f.input :is_e1en, :label => "E" %>
    <%= f.input :answer_6, placeholder: "请输入试题描述" %><%= f.input :is_f1en, :label => "F" %>
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "类别") %>

    <div class="group"> <p><b>CountDownDate</b></p>
      <%= f.datetime_field :countdown %><br>
      <%= @exam.countdown %>
    </div>

    <%= f.label :image %><br>
    <%= f.file_field :image, :multiple => true, name: "photos[image][]" %>（"这里可以上传图片"）<br>
    <%= f.submit "Submit", class: "btn btn-default" %>
  <% end %>

  <%= simple_form_for [@choice] do |f| %>
    <%= f.input :is_aa1en, :label => "A" %>
    <%= f.input :is_bb1en, :label => "B" %>
    <%= f.input :is_cc1en, :label => "C" %>
    <%= f.input :is_dd1en, :label => "D" %>
    <%= f.input :is_ee1en, :label => "E" %>
    <%= f.input :is_ff1en, :label => "F" %>
    <%= f.submit "Submit", class: "btn btn-default" %>
  <% end %>
</div>

app/views/admin/exams/show.html.erb
<br>
<div class="row">
  <div class="col-md-6">
    <% if @photos.present? %>
      <% @photos.each_with_index do |p, index| %>
        <% if index == 0 %>
          <%= image_tag p.image.medium.url %>
        <% else %>
          <%= image_tag p.image.thumb.url %>
        <% end %>
      <% end %>
    <% else %>
      <h4>本题无图</h4>
    <% end %>
  </div>
  <div class="col-md-6">
    <h2><%= @exam.question %></h2>
    <div style="height: 100px;">
      <hr>
      <p>正确答案</p>

      <p>
          <%= render_a1_status(@exam) %> A.<%= @exam.answer_1 %>
          <br><br>
          <%= render_b1_status(@exam) %> B.<%= @exam.answer_2 %>
          <br><br>
          <%= render_c1_status(@exam) %> C.<%= @exam.answer_3 %>
          <br><br>
          <%= render_d1_status(@exam) %> D.<%= @exam.answer_4 %>
      </p>

     <div>试题类别: <%= @exam.category_id %></div>
    </div>

  </div>
</div>