config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get '/info' => 'info#index'
  devise_for :users
  # devise_for :users, :controllers => {
  #   :sessions      => "users/sessions",
  #   :registrations => "users/registrations",
  #   :passwords     => "users/passwords",
  # }
  resources :products do
    member do
      post :add_to_cart
      post :favorite
      post :unfavorite
      post :instant_buy
    end
    collection do
      get :my_course
      get :search
    end
    resources :reviews, only: [:new, :create]
  end

  namespace :admin do
    resources :quizzes do
      resources :questions
    end
    resources :categories
    resources :products
    resources :posts
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end


  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :cart_items

  resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end

  namespace :account do
    resources :orders
  end

  resources :favorites


  resources :quizzes do
    member do
      post :exam_records
    end
    resources :questions
  end

  root "welcome#index"

  get 'about' => 'welcome#about'

  post "set_answer_1_status" => "answers#set_answer_1_status"
  post "set_answer_2_status" => "answers#set_answer_2_status"
  post "set_answer_3_status" => "answers#set_answer_3_status"
  post "set_answer_4_status" => "answers#set_answer_4_status"


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout "welcome"
  after_action :intercom_shutdown, only: [:index]

  def index
  
  end

  def about
  end

  protected
  def intercom_shutdown
    IntercomRails::ShutdownHelper.intercom_shutdown(session, cookies)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<div class="col-md-8 col-md-offset-2 about-page" style="margin-top: 100px;">
  <h4>翻越高考</h4>

   <br>

     <p>
      翻越高考 是由一群追求进步，热爱成长的全栈营学员互相帮扶的作品
      </br>
      经历了一个user story从无到有的过程
      </br>
      虽然实现的页面十分丑陋 目前也只有判断题和选择题 但是 一定要敢于迈出这一步
      </br>
      不怕丑 只为学
    </p>
  </br>

  <h4>挑战自我</h4>
   </br>
    <p>
      这里没有慵懒和迷茫
     </br>
      这里充满学习的乐趣和交友的乐趣
     </br>
      每个人都在付出自己的努力来完成曾经自己许下的诺言
     </br>
      只为践行
     </br>

    </p>
  </br>
  <h4>踏实落地</h4>

   </br>
    <p>

      拒绝慵懒拒绝迷茫 学会与焦虑共同成长 从而摆脱焦虑
      </br>
      挑战自我 狼性践行
      </br>
      再小的功能都要做 再烂的代码都要写
    </p>
    <br>

  <h4>@全栈营伙伴们.all.加油!</h4>

  <hr>

    <p>
      翻 越 高 考<br>
    </p>

  <%= link_to("返回首页", root_path) %>

</div>

app/views/welcome/index.html.erb
<!--- Header section  -->
<div class="container-fluid">
  <div class="row">
    <header class="main-header">
      <div class="header-inner">

        <div class="header-center">
          <a href="/">翻 越 高 考</a>
        </div>

        <div class="header-left pull-left">
          <!-- Search area -->
          <%= form_tag search_products_path , :method => :get, :class => "form-search" do %>
            <input type="text", class="search-input", name="q" value="<%= params[:q] %>" placeholder="请输入关键词搜索...">
            <button type="submit" class="search-icon">
              <span class="fa fa-search fa-lg"></span>
            </button>
          <% end %>
          <!-- End Search -->
        </div>

        <div class="header-right pull-right">
          <ul class="nav navbar-nav navbar-right">

            <li>
              <%= link_to products_path do %>
                 <i class="fa fa-home fa-lg"></i>题库中心
              <% end %>
            </li>
            <li>
              <%= link_to carts_path do %>
                购物车 <i class="fa fa-shopping-cart fa-lg"></i> (<%= current_cart.products.count %>)
              <% end %>
            </li>
            <% if !current_user %>
              <li>
                <div class="log-in">
                  <%= link_to("登录", new_user_session_path, class: "btn btn-xs header-user-item") %>
                </div>
              </li>
            <% else %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <% if current_user.nickname.present? %>
                    Hi, <%= current_user.nickname %>
                  <% else %>
                    Hi, <%= current_user.email %>
                  <% end %>
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <% if current_user.admin? %>
                    <li>
                      <%= link_to(content_tag(:i, " 后台管理", class: "fa fa-lock"), admin_products_path) %>
                    </li>
                  <% end %>
                  <li>
                    <%= link_to(content_tag(:i, " 我的题库", class: "fa fa-book"), account_orders_path) %>
                  </li>
                  <li>
                    <%= link_to(content_tag(:i, " 我的收藏", class: "fa fa-gratipay"), favorites_path ) %>
                  </li>
                  <li><%= link_to(content_tag(:i, " 编辑账户", class: "fa fa-pencil-square-o"),edit_user_registration_path) %></li>
                  <li>
                    <%= link_to(content_tag(:i, " 账户退出", class: "fa fa-sign-out"), destroy_user_session_path, method: :delete) %>
                  </li>
                </ul>
              </li>
            <% end %>
          </ul>
        </div>
      </div>

      <%= render "common/flashes" %>
    </header>

  </div>
</div>

<!---  end ----->

<!--- 首页动图 ----->

 <div class="banner-v2" >
   <div class="banner-detail">
     <!-- <h2 class="banner-logo ">

     </h2> -->
     <div  class="banner-slogan">
       <h1>

         <script src="/bower_components/jquery.countdown/dist/jquery.countdown.js"></script>

       <p><span class="sub-slogan">翻越高考</span>--------学子们加油！！！ <br><br>
         距高考还有:  <br>
        <div id="getting-started"></div>
      </p>

       </h1>


     </div>
     <div class="welcome-button">
         <%= link_to(content_tag(:i, '开始学习', class: 'fa fa-hand-o-right'), products_path,  class: "btn btn-primary-welcome") %>
      </div>
     </div>

  <div class="banner-img">
    <div id="myCarousel" class="carousel slide">
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
     </ol>
     <div class="carousel-inner">
        <div class="item active">
         <a href="javacript:;">
          <img src="https://ws4.sinaimg.cn/large/006tNc79ly1fg702kscljj30zk0jgdgp.jpg" />
          <div class="carousel-caption"></div>
         </a>
        </div>
        <div class="item">
         <a href="javacript:;">
          <img src="https://ws4.sinaimg.cn/large/006tNc79ly1fg702l5y4fj30zk0jg0ug.jpg" />
          <div class="carousel-caption"></div>
         </a>
        </div>
        <div class="item">
         <a href="javacript:;">
          <img src="https://ws4.sinaimg.cn/large/006tNc79ly1fg702kfhn6j30zk0jgact.jpg" />
          <div class="carousel-caption"></div>
         </a>
        </div>
      </div>
    </div>
  </div>



</div>


<!-- end 首页动图 ----->

<!-- 1 -->

<div class="lp-section-3 clearfix">
  <div class="content-3">
    <div class="feature-title">
      <div class="short-line"></div>
      <h2>历年各省高考试题</h2>
    </div>
    <div class="feature-block">
      <%= link_to products_path(category: "全国卷") do %>

        <img id="trip1" src="https://ws2.sinaimg.cn/large/006tNc79ly1fg706jvfi5j30sg0izaaf.jpg">

        <br>

        <h3>全国卷</h3>

      <% end %>
    </div>
    <div class="feature-block">
      <%= link_to products_path(category: "山东卷") do %>

        <img id="trip1" src="https://ws1.sinaimg.cn/large/006tNc79ly1fg706k2mtzj30sg0izt8v.jpg">

        <br>

        <h3>山东卷</h3>

      <% end %>
    </div>
    <div class="feature-block">
      <%= link_to products_path(category: "江苏卷") do %>

        <img id="trip1" src="https://ws4.sinaimg.cn/large/006tNc79ly1fg706jnoalj30sg0ko0uv.jpg">

        <br>

        <h3>江苏卷</h3>

      <% end %>
    </div>
    <div class="feature-block">
      <%= link_to products_path(category: "北京卷") do %>

        <img id="trip1" src="https://ws1.sinaimg.cn/large/006tNc79ly1fg70olwl30j30sg0izaan.jpg">

        <br>

        <h3>北京卷</h3>

      <% end %>
    </div>
    <div class="feature-block">
      <%= link_to products_path(category: "四川卷") do %>

        <img id="trip1" src="https://ws1.sinaimg.cn/large/006tNc79ly1fg70qnc6y3j30sg0f0go0.jpg">

        <br>

        <h3>四川卷</h3>

      <% end %>
    </div>
    <div class="feature-block">
      <%= link_to products_path(category: "上海卷") do %>

        <img id="trip1" src="https://ws2.sinaimg.cn/large/006tNc79ly1fg706iibw7j30sg0izmxo.jpg">

        <br>

        <h3>上海卷</h3>

      <% end %>
    </div>
  </div>
</div>

<!-- 2 -->
<div class="part2">
    <div class="content-3">
      <div class="feature-title">
        <div class="short-line"></div>
        <h2>我们的服务</h2>
        <div class="row">
        <div class="col-md-3 text-center wow fadeInLeft ">
            <div>
                <i style="color: #1ab394;font-size: 40px;" class="fa fa-bank features-icon"></i>
                <h2><a class="text-primary" href="/question">官方题库</a></h2>
                <p style="color: #aeaeae; ">全面收录市面上所有的高考真题，紧跟学习节奏，持续增加。</p>
            </div>
            <div class="m-t-lg">
                <i style="color: #1ab394;font-size: 40px;" class="fa fa-balance-scale features-icon"></i>
                <h2>
                    <a class="text-primary" href="/exercise">练习</a>                </h2>
                <p style="color: #aeaeae">定制化的高考计划 <strong>刷题利器</strong>。帮你轻松刷题，并针对某些题型、考点或知识点进行测验</p>
            </div>
            <div class="m-t-lg">
                <i style="color: #1ab394;font-size: 40px;" class="fa fa-tv features-icon"></i>
                <h2><a class="text-primary" href="/live">直播</a></h2>
                <p style="color: #aeaeae">观看老师定期举办的在线公开课，化解考试的难题和错题。</p>
            </div>

        </div>
        </a>

        <div class="col-md-6 text-center m-t-xl wow zoomIn ">
            <img src="//img.gmat.la/pages/home/screenshot_question.png" alt="gmat 考题界面" class="img-responsive m-t-xl">
        </div>

        <div class="col-md-3 text-center wow fadeInRight " style="visibility: visible; animation-name: fadeInRight;">
            <div>
                <i style="color: #1ab394;font-size: 40px;" class="fa fa-wikipedia-w features-icon"></i>
                <h2>
                    <a class="text-primary" href="/wiki">百科</a>                </h2>
                <p style="color: #aeaeae">与高考真题相关的一切知识统一整理在此。新手上路？科普页面给你开始备考之路的一切信息。</p>
            </div>
            <div class="m-t-lg">
                <i style="color: #1ab394;font-size: 40px;" class="fa fa-blind features-icon"></i>
                <h2><a class="text-primary" href="/exam">模考</a></h2>
                <p style="color: #aeaeae">真实的原题，交卷后还有用时统计和强弱项分析等报告。</p>
            </div>
            <div class="m-t-lg">
                <i style="color: #1ab394;font-size: 40px;" class="fa fa-graduation-cap features-icon"></i>
                <h2>
                    <a class="text-primary" href="/curriculum/GMAT%E9%9D%A2%E6%8E%88%E7%8F%AD">课程</a>                </h2>
                <p style="color: #aeaeae">不想孤军奋战？参加翻越高考面授课程，让老师传授你考试提分的独家秘诀！</p>
            </div>

        </div>
    </div>
      </div>
      </div>

</div>
<!-- <div class="part2">
<section id="testimonial" class="talk-about-us">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 col-xs-12 text-center">
        <div class="short-line"></div>
        <h2 class="section-title">资讯</h2>
        <div id="talk-about-us" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#talk-about-us" data-slide-to="0" class="active"></li>
            <li data-target="#talk-about-us" data-slide-to="1" class=""></li>
            <li data-target="#talk-about-us" data-slide-to="2" class=""></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="item active">
              <strong>资讯标题</strong>
              <img src="https://ws3.sinaimg.cn/large/006tNbRwly1ffzqpcmomtj30hs0bu3zj.jpg" alt="资讯">
              <p>。。。。。。。。。。。。。。此处省略n个字。。。。。。。。。。。。。。。。。</p>
            </div>
            <div class="item">
              <strong>资讯标题</strong>
              <img src="https://ws3.sinaimg.cn/large/006tNbRwly1ffzqp78kr6j30hs0ay0t3.jpg" alt="资讯">
              <p>。。。。。。。。。。。。。。此处省略n个字。。。。。。。。。。。。。。。。。</p>
            </div>
            <div class="item">
              <strong>资讯标题</strong>
              <img src="https://ws3.sinaimg.cn/large/006tNbRwly1ffzqp7lw0uj30hs0bugme.jpg" alt="资讯">
              <p>。。。。。。。。。。。。。。此处省略n个字。。。。。。。。。。。。。。。。。</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
</div> -->

<!-- 3 -->
<div class="lp-section-4 clearfix">
<div class="content_body_on">
  <br />
  <br />
  <div class="feature-title">
    <div class="short-line"></div>
    <h2 align="center">疑难解答</h2>
    <br />
  </div>
        <div class="content_body" style="padding: 55px 0px;">
            <ul class="banners clearfix">
              <li class="banners_li">
                    <a>
                        <img src="https://ws4.sinaimg.cn/large/006tNc79ly1fg70got94ej30iz0izdge.jpg"><div>
                            <h3>模拟考有老师解答吗？</h3>
                            <p>由50位专业老师精心打造的模拟试题，配有专业解答，如有需要，可预约导师一对一辅导。 </p>
                        </div>
                    </a>
                </li>
                <li class="banners_li">
                    <a>
                        <img src="https://ws3.sinaimg.cn/large/006tNc79ly1fg70iq7r2jj30iz0izq38.jpg"><div>
                            <h3>有论坛讨论问题吗？</h3>
                            <p >关于高考的一切大家都在这里讨论，来这里寻找与你志同道合的考友。</p>
                        </div>
                    </a>
                </li>
                <li class="banners_li banners_li_last">
                    <a>
                        <img src="https://ws1.sinaimg.cn/large/006tNc79ly1fg70iqgvruj30iz0izaa6.jpg"><div>
                            <h3>可以加入学习小组吗？</h3>
                            <p>我们全方位打造优质的学习小组，加入我们的学习小组，由真人小助手每天发给你备考资料、每日一题、换库通知等等。 </p>
                        </div>
                    </a>
                </li>
            </ul>
        </div>
    </div>
  </div>
<!-- 4 -->
<div class="lp-section-6 clearfix">
  <div class="content-3">
    <div class="feature-title">
      <h4 align="center"; class="oblique">We have a new way of answering and research ideas and help students understand the problem.</h4>
      <br/>
      <br/>


          <%= link_to( "开始学习" ,products_path, class: "btn btn-lg btn-info") %>

    </div>
</div>
</div>

<!-- 5 -->
  <div class="short-line"></div>
  <p class="des">合作企业</p>
  <div class="content-4 content-5">

    <div class="list">
      <img src="http://ww4.sinaimg.cn/large/006tNc79ly1fewpf5hhalj305x022mxv.jpg">
      <img src="http://ww1.sinaimg.cn/large/006tNc79ly1fewpnfd2t2j30e804e74h.jpg">
      <img src="http://ww4.sinaimg.cn/large/006tNc79ly1fewprmgcoyj3064032dg5.jpg">
      <img src="http://ww4.sinaimg.cn/large/006tNc79ly1fewpwzvpavj30go04f0tm.jpg">
      <img src="http://ww3.sinaimg.cn/large/006tNc79ly1fewqh0j6wxj30hh03zjs6.jpg">
      <img src="http://ww1.sinaimg.cn/large/006tNc79ly1fewu4mqhd2j30p00b40u1.jpg">
      <img src="http://ww3.sinaimg.cn/large/006tNc79ly1fewrgtfr3vj30p005ymz4.jpg">
      <img src="http://ww2.sinaimg.cn/large/006tNc79ly1fewrrtgzo5j30p005y75x.jpg">
      <img src="http://ww2.sinaimg.cn/large/006tNc79ly1fewrxe81saj30p007740p.jpg">
    </div>
    </div>
    <br />

    <br />
    <br />

</div>
</div>

<!--    我新加的 完    -->




<!-- Footer -->


<div class="footer">
  <div class="copyright">
    <div class="design">
      <span><%= link_to '关于我们', about_path %></span>  <span><%= link_to '联系我们', about_path %></span>
      <p>@Copyright 2017 翻越高考
      <p>全栈营学员</p>
    </div>
  </div>
</div>

<!-- End of Footer -->

<!-- countdown -->


<script type="text/javascript">
  $("#getting-started")

  .countdown("2017/06/07", function(event) {
    $(this).text(
      event.strftime('%D 天 %H:%M:%S')
    );
  });
</script>