config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get '/info' => 'info#index'
  devise_for :users
  # devise_for :users, :controllers => {
  #   :sessions      => "users/sessions",
  #   :registrations => "users/registrations",
  #   :passwords     => "users/passwords",
  # }
  resources :products do
    member do
      post :add_to_cart
      post :favorite
      post :unfavorite
      post :instant_buy
    end
    collection do
      get :my_course
      get :search
    end
    resources :reviews, only: [:new, :create]
  end

  namespace :admin do
    resources :quizzes do
      resources :questions
    end
    resources :categories
    resources :products
    resources :posts
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end


  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :cart_items

  resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end

  namespace :account do
    resources :orders
  end

  resources :favorites


  resources :quizzes do
    member do
      post :exam_records
    end
    resources :questions
  end

  root "welcome#index"

  get 'about' => 'welcome#about'

  post "set_answer_1_status" => "answers#set_answer_1_status"
  post "set_answer_2_status" => "answers#set_answer_2_status"
  post "set_answer_3_status" => "answers#set_answer_3_status"
  post "set_answer_4_status" => "answers#set_answer_4_status"


end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product
  has_many :posts, through: :cart_items, source: :post

  def add_product_to_cart(product)
    ci = cart_items.build
    ci.product = product
    ci.quantity = 1
    ci.save
  end

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum += cart_item.quantity * cart_item.product.price
      end
    end
    sum
  end

  def clean!
    cart_items.destroy_all
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, only: [:checkout]
  def clean
    current_cart.clean!
    flash[:warning] = "已清空购物车"
    redirect_to carts_path
  end

  def checkout
    @order = Order.new
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
    cart.total_price
  end
end

app/views/carts/checkout.html.erb
<div class="row checkout-page">
  <div class="col-md-8 col-md-offset-2">
    <div class="shopping-cart" style="margin-top: 50px;">
      <div class="column-labels">
        <label class="product-image">商品</label>
        <label class="product-price">单价</label>
        <label class="product-quantity">数量</label>
        <label class="product-line-price">小计</label>
        <label class="actual-pay">实付</label>
      </div>
      <% current_cart.cart_items.each do |cart_item| %>
        <div class="product">
          <div class="product-image">
            <%= link_to product_path(cart_item.product) do %>
              <% if cart_item.product.photos.present? %>
                <%= image_tag(cart_item.product.photos[0].image.thumb.url) %>
              <% else %>
                <%= image_tag("http://placehold.it/200x200&text=No Pic") %>
              <% end %>
            <% end %>
          </div>
          <div class="product-price">￥<%= cart_item.product.price %></div>
          <div class="product-quantity">
            <%= cart_item.quantity %>
          </div>
          <div class="product-line-price">
            <%= cart_item.product.price * cart_item.quantity %> RMB
          </div>
          <div class="product-line-price">
            <%= cart_item.product.price * cart_item.quantity %> RMB
          </div>
        </div>
      <% end %>

      <div class="total-order clearfix">
        <div>
          商品合计：<span><%= render_cart_total_price(current_cart) %> CNY</span>
        </div>
        <div>
          总计： <span><%= render_cart_total_price(current_cart)  %> CNY</span>
        </div>
      </div>

    </div>
    <div class="order-form">
      <%= simple_form_for @order do |f| %>
        <legend>付款信息</legend>
        <div class="form-group col-lg-6">
          <%= f.input :billing_name, label: "付款人" %>
        </div>
        <div class="form-group col-lg-6">
          <%= f.input :billing_address, label: "付款地址" %>
        </div>
        <legend>收货信息</legend>
        <div class="form-group col-lg-6">
          <%= f.input :shipping_name, label: "收货人" %>
        </div>
        <div class="form-group col-lg-6">
          <%= f.input :shipping_address, label: "收获地址" %>
        </div>
        <div class="checkout text-center">
          <%= f.submit "生成订单", class: "btn btn-lg btn-danger", data: {disable_with: "Submitting..."} %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/carts/index.html.erb
<div class="row cart-page">
  <div class="col-md-8 col-md-offset-2">
    <h4>购物车宝贝~</h4>
    <span class="pull-right">
      <%= link_to("清空购物车", clean_carts_path, method: :delete, class: "pull-right",
          style:"color: #ef5350;", data: {confirm: "你确定要清空整个购物车吗？"}) %>
    </span>

    <div class="shopping-cart" style="margin-top: 50px;">
      <div class="column-labels">
        <label class="product-image">商品</label>
        <label class="product-price">单价</label>
        <label class="product-quantity">数量</label>
        <label class="product-removal">操作</label>
        <label class="product-line-price">小计</label>
      </div>
      <% current_cart.cart_items.each do |cart_item| %>
        <div class="product">
          <div class="product-image">
            <%= link_to product_path(cart_item.product) do %>
              <% if cart_item.product.photos.present? %>
                <%= image_tag(cart_item.product.photos[0].image.thumb.url) %>
              <% else %>
                <%= image_tag("http://placehold.it/200x200&text=No Pic") %>
              <% end %>
            <% end %>
          </div>
          <div class="product-price">￥<%= cart_item.product.price %></div>
          <div class="product-quantity">

              <%= 1 %>

          
          </div>
          <div class="product-removal">
            <button class="remove-product">
              <%= link_to("移除商品", cart_item_path(cart_item.product_id), method: :delete)  %>
            </button>
          </div>
          <div class="product-line-price">
            <%= cart_item.product.price * cart_item.quantity %> RMB
          </div>
        </div>
      <% end %>

      <div class="totals pull-right">
        <div class="totals-item">
          <div class="totals-value" id="cart-subtotal">
            <b>总计：</b><%= render_cart_total_price(current_cart) %> RMB
          </div>
        </div>
        <br>
        <%= link_to("确认结账", checkout_carts_path, method: :post, class: "checkout-btn") %>
      </div>
    </div>
  </div>
</div>