config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get '/info' => 'info#index'
  devise_for :users
  # devise_for :users, :controllers => {
  #   :sessions      => "users/sessions",
  #   :registrations => "users/registrations",
  #   :passwords     => "users/passwords",
  # }
  resources :products do
    member do
      post :add_to_cart
      post :favorite
      post :unfavorite
      post :instant_buy
    end
    collection do
      get :my_course
      get :search
    end
    resources :reviews, only: [:new, :create]
  end

  namespace :admin do
    resources :quizzes do
      resources :questions
    end
    resources :categories
    resources :products
    resources :posts
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end


  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :cart_items

  resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end

  namespace :account do
    resources :orders
  end

  resources :favorites


  resources :quizzes do
    member do
      post :exam_records
    end
    resources :questions
  end

  root "welcome#index"

  get 'about' => 'welcome#about'

  post "set_answer_1_status" => "answers#set_answer_1_status"
  post "set_answer_2_status" => "answers#set_answer_2_status"
  post "set_answer_3_status" => "answers#set_answer_3_status"
  post "set_answer_4_status" => "answers#set_answer_4_status"


end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  layout 'info'
  def index
  end
end

app/helpers/info_helper.rb
module InfoHelper
end

app/views/info/index.html.erb
<div class="info col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
  <p class="info-nav">
    <a href="/">首页</a> > 咨询
  </p>
  <img src="https://ww4.sinaimg.cn/large/006tNbRwly1fcz5sjwlcnj30wt0esdh2.jpg">
  <h1>10款融入暖意的幸福大课</h1>
  <h4 class="info-time">2017年5月x日</h4>
  <div id="info">
    <div class="col-md-8 col-sm-8 info-content">

     <p>
       品尝美食是一种刺激多重观感的体验，所以除了基本的色香味三要素之外，比较讲究的餐厅和家庭都会在餐具、摆盘，甚至是用餐环境上多花点铁思，以提升视觉效果和整个用餐体验，因此，如今的杯碟碗筷已经不再只是餐具容器那么单纯。
     </p>
     <p>
       今天要为大家推荐的10款幸福课
     </p>

     <h3>1.裸女浸浴茶杯套裝</h3>
     <img src="https://ww4.sinaimg.cn/large/006tNbRwly1fcz6xjp5bvj30i20fyglw.jpg">
     <img src="https://ww3.sinaimg.cn/large/006tNbRwly1fcz6y90814j30i20i2glz.jpg">
     <p>Image credits: <a href="http://hetparadijs.net/en/shop/tableware/undressed-tea-set"> Esther Horchner</a></p>

     <h3>2.渔人茶杯</h3>
     <img src="https://ww3.sinaimg.cn/large/006tNbRwly1fcz76wikl4j30i20i20tc.jpg">
     <p>Image credits: <a href="http://womany.net/shop/item/638"> womany.net</a></p>

     <h3>3.曲奇怪兽茶杯（杯底位置的缺口可以用来放曲奇哦！）</h3>
     <img src="https://ww1.sinaimg.cn/large/006tNbRwly1fcz7aaehzoj30i20c03z9.jpg">
     <img src="https://ww1.sinaimg.cn/large/006tNbRwly1fcz7ae8qboj30i20c0gm3.jpg">
     <p>Image credits: <a href="https://www.etsy.com/listing/104935165/googly-eyed-monster-dunk-mug-ceramic"> Etsy</a></p>

     <h3>4.动物咖啡杯（章鱼...那个有点让人铁慌...）</h3>
     <img src="https://ww1.sinaimg.cn/large/006tNbRwly1fcz7dmr3z8j30i20dkq32.jpg">
     <img src="https://ww4.sinaimg.cn/large/006tNbRwly1fcz7dswysaj30i20h074o.jpg">
     <p>Image credits: <a href="https://www.amazon.com/s/?_encoding=UTF8&camp=1789&creative=390957&field-keywords=creature%20cups&linkCode=ur2&rh=i%3Aaps%2Ck%3Acreature%20cups&sprefix=creature%20cu%2Caps&tag=vilofjoy-20&url=search-alias%3Daps"> Amazon</a></p>

     <h3>5.熊猫笑脸杯碟套裝（杯碟放一起，熊猫先生才会开铁哦！）</h3>
     <img src="https://ww2.sinaimg.cn/large/006tNbRwly1fcz7r6t3xsj30i20ez74h.jpg">
     <p>Image credits: <a href="http://www.boredpanda.com/panda-smile-on-your-face-mug-set/"> modcloth.com</a></p>

     <h3>6.长劲鹿咖啡杯</h3>
     <img src="https://ww4.sinaimg.cn/large/006tNbRwly1fcz7sqtk8nj30i20i2aav.jpg">
     <p>Image credits: <a href="https://www.amazon.com/Homee-Hand-Painted-Ceramic-Giraffe-Style/dp/B00GOR9GGW/ref=as_sl_pc_ss_til?tag=bplin-20&linkCode=w01&linkId=&creativeASIN=B00GOR9GGW"> Amazon</a></p>

     <h3>7.长尾巴的咖啡杯</h3>
     <img src="https://ww3.sinaimg.cn/large/006tNbRwly1fcz7pckxh2j30i20c3aac.jpg">
     <img src="https://ww3.sinaimg.cn/large/006tNbRwly1fcz7petmwdj30i20c3jrl.jpg">
     <p>Image credits: <a href="https://www.amazon.com/s/?_encoding=UTF8&camp=1789&creative=390957&field-keywords=mugtail&linkCode=ur2&rh=i%3Aaps%2Ck%3Amugtail&sprefix=mugta%2Caps&tag=vilofjoy-20&url=search-alias%3Daps"> Amazon</a></p>

     <h3>8.Ironius：可以当熨斗用的咖啡杯（不过用起來要小铁，别把咖啡洒到衣服上哦！）</h3>
     <img src="https://ww1.sinaimg.cn/large/006tNbRwly1fcz7wcum4zj30i20kyjs1.jpg">
     <img src="https://ww2.sinaimg.cn/large/006tNbRwly1fcz7wdioiyj30i208274a.jpg">
     <p>Image credits: <a href="http://www.boredpanda.com/ironius-the-coffee-mug-iron-pic/"> Art Lebedev Studio</a></p>

     <h3>9.手榴弹咖啡杯</h3>
     <img src="https://ww2.sinaimg.cn/large/006tNbRwly1fcz7z87cyqj30i20c1q38.jpg">
     <p>Image credits: <a href="http://www.ckie.com/products/grenade-mug"> Etsy</a></p>

     <h3>10.键盘咖啡杯套裝 （可以送给电脑迷做礼物哦！）</h3>
     <img src="https://ww4.sinaimg.cn/large/006tNbRwly1fcz82or6iuj30i20ni74n.jpg">
     <img src="https://ww3.sinaimg.cn/large/006tNbRwly1fcz82qj3uxj30i20dldfv.jpg">
     <img src="https://ww4.sinaimg.cn/large/006tNbRwly1fcz82t5v29j30i20ekaae.jpg">
     <p>Image credits: <a href="https://www.amazon.com/Finger-Salute-Coffee-Breaks-Ctrl-Alt-Delete/dp/B00MJ0DCH2/ref=sr_1_3?s=kitchen&ie=UTF8&qid=1487744235&sr=1-3&keywords=keyboard+coffee"> Amazon</a></p>

    </div>
    <div class="col-md-4 proposal-product">
      <h4 style="padding-top:10px;">为您推荐的宝贝</h4>
      <hr />
      <div id="pins" class="transitions-enabled">
        <% Product.limit(6).sort_by{|product| -product.fans.count}.each do |product| %>
          <div class="box " style="padding:0px;">

            <%= link_to product_path(product) do %>
              <% if product.photos.present? %>
                <%= image_tag(product.photos[0].image.url) %>
              <% else %>
                <%= image_tag("http://placehold.it/200x200&text=No Pic") %>
              <% end %>
            <% end %>

            <div class="fig" >

              <p class="actions">
                  <% if product.quantity.present? && product.quantity > 0 %>
                    <%= link_to("去看看", product_path(product), class: "add-to-cart btn", style: "height:26px;font-size:11px;background-color:rgb(245,190,126);", :method => :get) %>
                  <% else %>
                    已售馨
                  <% end %>

                  <% if product.quantity.present? && product.quantity > 0 %>
                    <%= link_to("加入购物车", add_to_cart_product_path(product), class: "add-to-cart btn ", style: "height:26px;font-size:11px;border-color:rgb(245,190,126);background-color:#fff;color:rgb(245,190,126); ", :method => :post) %>
                  <% else %>
                    已销售一空，无法购买
                  <% end %>

                  <% if user_signed_in? %>
                    <% if !current_user.is_fan_of?(product) %>
                      <%= link_to favorite_product_path(product), :class => "like btn btn-default", style: "height:26px;font-size:11px;border-color:rgb(245,190,126);background-color:rgb(245,190,126); ", method: :post do %>
                        <i class="fa fa-heart fa-lg", style="border-color:#fff;color:#fff;"></i>
                      <% end %>
                    <% else %>
                      <%= link_to unfavorite_product_path(product), :class => "like btn btn-default",style: "height:26px;font-size:11px;border-color:rgb(245,190,126); ", method: :post do %>
                        <i class="fa fa-heart fa-lg", style="color:rgb(245,190,126);"></i>
                      <% end %>
                    <% end %>
                  <% else %>
                    <%= link_to favorite_product_path(product), :class => "like btn btn-default", style: "height:26px;font-size:11px;border-color:rgb(245,190,126)", method: :post do %>
                      <i class="fa fa-heart-o fa-lg", style="color:rgb(245,190,126);"></i>
                    <% end %>
                  <% end %>
              </p>
              <p  style="font-size:12px;text-align:left;padding-left:12px;margin-top:10px;"><%= product.title %></p>
              <p  style="font-size:12px;text-align:left;padding-left:12px;color:#999">￥ <%= product.price %> </p>

            </div>

          </div>
        <% end %>
      </div>
    </div>
  </div>

</div>